/* Generated by Cython 3.2.4 */

#ifndef __PYX_HAVE_API__cy_umfpack_wrapper
#define __PYX_HAVE_API__cy_umfpack_wrapper
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static int (*__pyx_api_f_18cy_umfpack_wrapper_cy_solve_sparse_system)(double *, int *, int *, int, int, int, double *, double *) = 0;
#define cy_solve_sparse_system __pyx_api_f_18cy_umfpack_wrapper_cy_solve_sparse_system
static int (*__pyx_api_f_18cy_umfpack_wrapper_cy_factorize_sparse_system)(double *, int *, int *, int, int, int, int64_t *) = 0;
#define cy_factorize_sparse_system __pyx_api_f_18cy_umfpack_wrapper_cy_factorize_sparse_system
static int (*__pyx_api_f_18cy_umfpack_wrapper_cy_solve_with_factors)(int64_t, double *, double *, int) = 0;
#define cy_solve_with_factors __pyx_api_f_18cy_umfpack_wrapper_cy_solve_with_factors
static int (*__pyx_api_f_18cy_umfpack_wrapper_cy_free_sparse_factors)(int64_t) = 0;
#define cy_free_sparse_factors __pyx_api_f_18cy_umfpack_wrapper_cy_free_sparse_factors
static int __Pyx_ImportFunction_3_2_4(PyObject *module, const char *funcname, void (**f)(void), const char *sig);

#ifndef __PYX_HAVE_RT_ImportFromPxd_3_2_4
#define __PYX_HAVE_RT_ImportFromPxd_3_2_4
static int __Pyx_ImportFromPxd_3_2_4(PyObject *module, const char *name, void **p, const char *sig, const char *what) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
#if (defined(Py_LIMITED_API) && Py_LIMITED_API >= 0x030d0000) || (!defined(Py_LIMITED_API) && PY_VERSION_HEX >= 0x030d0000)
    PyDict_GetItemStringRef(d, name, &cobj);
#else
    cobj = PyDict_GetItemString(d, name);
    Py_XINCREF(cobj);
#endif
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C %.8s %.200s",
                PyModule_GetName(module), what, name);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C %.8s %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             what, PyModule_GetName(module), name, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    *p = PyCapsule_GetPointer(cobj, sig);
    if (!(*p))
        goto bad;
    Py_DECREF(d);
    Py_DECREF(cobj);
    return 0;
bad:
    Py_XDECREF(d);
    Py_XDECREF(cobj);
    return -1;
}
#endif

#ifndef __PYX_HAVE_RT_ImportFunction_3_2_4
#define __PYX_HAVE_RT_ImportFunction_3_2_4
static int __Pyx_ImportFunction_3_2_4(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    int result = __Pyx_ImportFromPxd_3_2_4(module, funcname, &tmp.p, sig, "function");
    if (result == 0) {
        *f = tmp.fp;
    }
    return result;
}
#endif


static int import_cy_umfpack_wrapper(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("cy_umfpack_wrapper");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_3_2_4(module, "cy_solve_sparse_system", (void (**)(void))&__pyx_api_f_18cy_umfpack_wrapper_cy_solve_sparse_system, "int (double *, int *, int *, int, int, int, double *, double *)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_2_4(module, "cy_factorize_sparse_system", (void (**)(void))&__pyx_api_f_18cy_umfpack_wrapper_cy_factorize_sparse_system, "int (double *, int *, int *, int, int, int, int64_t *)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_2_4(module, "cy_solve_with_factors", (void (**)(void))&__pyx_api_f_18cy_umfpack_wrapper_cy_solve_with_factors, "int (int64_t, double *, double *, int)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_2_4(module, "cy_free_sparse_factors", (void (**)(void))&__pyx_api_f_18cy_umfpack_wrapper_cy_free_sparse_factors, "int (int64_t)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__cy_umfpack_wrapper */
