name: Build Wheels

on:
  workflow_dispatch:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
#  release:
#    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Add the MinGW setup here, after Python setup and before building
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Configure pip for MinGW
        run: |
          echo "[build]" > $HOME/.distutils.cfg
          echo "compiler=mingw32" >> $HOME/.distutils.cfg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.12.1

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          echo "INCLUDE_DIRS path check:"
          ls -la vendor/suitesparse/include || echo "Path not found"
          ls -la sparse_numba/vendor/suitesparse/include || echo "Path not found"

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp${{ matrix.python }}-win_amd64
          CIBW_BEFORE_BUILD: pip install numpy cython numba
#          CIBW_ENVIRONMENT: "INCLUDE_DIRS=sparse_numba/vendor/suitesparse/include;sparse_numba/vendor/openblas/include LIB_DIRS=sparse_numba/vendor/suitesparse/lib;sparse_numba/vendor/openblas/lib"
          CIBW_ENVIRONMENT: "INCLUDE_DIRS=vendor/suitesparse/include;vendor/openblas/include LIB_DIRS=vendor/suitesparse/lib;vendor/openblas/lib"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl